from datetime import datetime
from typing import Any

from jinja2 import Template

DEFAULT_TEMPLATE = """# {{ title }}

**周期**: {{ window_start }} ~ {{ window_end }}  
**仓库**: {{ repo_list }}

## 提交概览

{% if commits %}
| 仓库 | 提交 | 说明 | 作者 | 时间 |
|------|------|------|------|------|
{% for c in commits -%}
| `{{ c.repo }}` | [{{ c.sha }}]({{ c.url }}) | {{ c.message | e }} | {{ c.author | e }} | {{ c.date }} |
{% endfor %}
{% else %}
本周所选时间窗内无匹配提交（或 Token 权限不足 / 仓库名格式应为 `owner/repo`）。
{% endif %}

## 备注

{{ footer }}
"""


def render_report_markdown(
    commits: list[dict[str, Any]],
    profile_name: str,
    window_days: int,
    repos: list[str],
    style: dict[str, Any],
) -> str:
    language = style.get("language", "zh")
    tone = style.get("tone", "neutral")
    title = style.get("title") or ("Weekly Report" if language == "en" else "工作周报")
    footer = style.get("footer") or (
        "Generated by week-report."
        if language == "en"
        else "由 week-report 自动生成，请核对链接与事实后发送。"
    )
    if tone == "brief" and language == "zh":
        title = profile_name + " · 简报"

    now = datetime.utcnow()
    window_end = now.strftime("%Y-%m-%d")
    from datetime import timedelta

    window_start = (now - timedelta(days=window_days)).strftime("%Y-%m-%d")
    body_tpl = style.get("markdown_template") or DEFAULT_TEMPLATE
    tpl = Template(body_tpl)
    return tpl.render(
        title=title,
        window_start=window_start,
        window_end=window_end,
        window_days=window_days,
        repo_list=", ".join(repos),
        commits=commits,
        footer=footer,
        profile_name=profile_name,
    )
