from datetime import datetime, timedelta
from typing import Any

from jinja2 import Template

from app.template_presets import resolve_markdown_template_string


def render_report_markdown(
    commits: list[dict[str, Any]],
    profile_name: str,
    window_days: int,
    repos: list[str],
    style: dict[str, Any],
) -> str:
    language = style.get("language", "zh")
    tone = style.get("tone", "neutral")
    title = style.get("title") or ("Weekly Report" if language == "en" else "工作周报")
    footer = style.get("footer") or (
        "Generated by week-report."
        if language == "en"
        else "由 week-report 自动生成，请核对链接与事实后发送。"
    )
    if tone == "brief" and language == "zh":
        title = profile_name + " · 简报"

    now = datetime.utcnow()
    window_end = now.strftime("%Y-%m-%d")
    window_start = (now - timedelta(days=window_days)).strftime("%Y-%m-%d")
    body_tpl = resolve_markdown_template_string(style)
    tpl = Template(body_tpl)
    return tpl.render(
        title=title,
        window_start=window_start,
        window_end=window_end,
        window_days=window_days,
        repo_list=", ".join(repos),
        commits=commits,
        footer=footer,
        profile_name=profile_name,
    )
